version: '2'

services:
  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: pycon-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "/tmp/pyconfr-ftp:/home/"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: pyconfr
      FTP_USER_PASS: pyconfr
      FTP_USER_HOME: /home/pyconfr
    restart: always
