site_name: pycon
site_description: Writing Integration tests with pytest
repo_url: https://github.com/maho/pycon
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/maho">maho</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
